---

banner: |-
  ****************************
           TRAINING
             cisco
         WS-C3650-24TS
    CAT3K_CAA-UNIVERSALK9-M
     IOS Version 03.06.08E
  ****************************


users: 
  user001: 
    {id: cisco,  password: cisco}

vtp_mode: transparent

add_vlan_id: "10,20,50"


vlan_interfaces: 
  vlan10: 
    name: "interface Vlan10"
    vlan_id: 10
    ipv4: "192.168.10.254"
    subnetmask: 24

  vlan20:
    name: "interface Vlan20"
    vlan_id: 20
    ipv4: "192.168.20.254"
    subnetmask: 24

  vlan50:
    name: "interface Vlan50"
    vlan_id: 50
    ipv4: "192.168.50.254"
    subnetmask: 24


port_channel: 
  channel10:
    name: "Port-channel10"
    channel_id: 10
    state: present
    switchport_mode: trunk
    switchport_vlan: "10,20"

interfaces:

  GigabitEthernet1/0/1:
    name: "interface GigabitEthernet1/0/1"
    status: enable
    channel_id: 10
    channel_mode: "on"
    description: "from L2SW"
    switchport_mode: trunk
    switchport_vlan: "10,20"

  GigabitEthernet1/0/2:
    name: "interface GigabitEthernet1/0/2"
    status: enable
    channel_id: 10
    channel_mode: "on"
    description: "from L2SW"
    switchport_mode: trunk
    switchport_vlan: "10,20"

  GigabitEthernet1/0/3:
    {name: "interface GigabitEthernet1/0/3", status: disable}

  GigabitEthernet1/0/4:
    {name: "interface GigabitEthernet1/0/4", status: disable}

  GigabitEthernet1/0/5:
    name: "interface GigabitEthernet1/0/5"
    status: enable
    description: "to SV"
    switchport_mode: access
    switchport_vlan: 50
    portfast: enable

  GigabitEthernet1/0/6:
    {name: "interface GigabitEthernet1/0/6", status: disable}

  GigabitEthernet1/0/7:
    {name: "interface GigabitEthernet1/0/7", status: disable}

  GigabitEthernet1/0/8:
    {name: "interface GigabitEthernet1/0/8", status: disable}

  GigabitEthernet1/0/9:
    {name: "interface GigabitEthernet1/0/9", status: disable}

  GigabitEthernet1/0/10:
    {name: "interface GigabitEthernet1/0/10", status: disable}

  GigabitEthernet1/0/11:
    {name: "interface GigabitEthernet1/0/11", status: disable}

  GigabitEthernet1/0/12:
    {name: "interface GigabitEthernet1/0/12", status: disable}

  GigabitEthernet1/0/13:
    {name: "interface GigabitEthernet1/0/13", status: disable}

  GigabitEthernet1/0/14:
    {name: "interface GigabitEthernet1/0/14", status: disable}

  GigabitEthernet1/0/15:
    {name: "interface GigabitEthernet1/0/15", status: disable}

  GigabitEthernet1/0/16:
    {name: "interface GigabitEthernet1/0/16", status: disable}

  GigabitEthernet1/0/17:
    {name: "interface GigabitEthernet1/0/17", status: disable}

  GigabitEthernet1/0/18:
    {name: "interface GigabitEthernet1/0/18", status: disable}

  GigabitEthernet1/0/19:
    {name: "interface GigabitEthernet1/0/19", status: disable}

  GigabitEthernet1/0/20:
    {name: "interface GigabitEthernet1/0/20", status: disable}

  GigabitEthernet1/0/21:
    {name: "interface GigabitEthernet1/0/21", status: disable}

  GigabitEthernet1/0/22:
    {name: "interface GigabitEthernet1/0/22", status: disable}

  GigabitEthernet1/0/23: 
    {name: "interface GigabitEthernet1/0/23", status: disable}

  GigabitEthernet1/0/24:
    name: "interface GigabitEthernet1/0/24"
    status: enable
    description: "to RT"
    ipv4: "192.168.254.1"
    subnetmask: 24

  GigabitEthernet1/1/1:
    {name: "interface GigabitEthernet1/1/1", status: disable}

  GigabitEthernet1/1/2:
    {name: "interface GigabitEthernet1/1/2", status: disable}

  GigabitEthernet1/1/3:
    {name: "interface GigabitEthernet1/1/3", status: disable}

  GigabitEthernet1/1/4:
    {name: "interface GigabitEthernet1/1/4", status: disable}

static_route:
  route001:
    prefix: 0.0.0.0
    mask: 0.0.0.0
    next_hop: 192.168.254.254
